# Generated by Django 6.0.7 on 2026-08-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_relatedpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationindexpage',
            name='lead',
            field=models.TextField(blank=True, help_text='Short lead paragraph shown in the page header.'),
        ),
    ]
