# Generated by Django 6.0.6 on 2026-07-11 05:38

import django.db.models.deletion
import modelsearch.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'resource folder',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=255, upload_to='resources')),
                ('resource_type', models.CharField(choices=[('pds', 'Product Data Sheet (PDS)'), ('sds', 'Safety Data Sheet (SDS)'), ('brochure', 'Brochure'), ('certificate', 'Certificate'), ('manual', 'Manual'), ('other', 'Other')], default='pds', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, default='en', help_text='ISO language code, e.g. en, fr, de', max_length=10)),
                ('revision_date', models.DateField(blank=True, help_text='Date of the current revision of this resource', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file_size', models.PositiveBigIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.resourcefolder')),
            ],
            options={
                'verbose_name': 'resource',
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
