# Generated by Django 6.0.6 on 2026-07-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_migrate_resourcedocuments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceDocument',
        ),
    ]
