# Generated by Django 6.0.6 on 2026-07-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_delete_resourcedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='label',
            field=models.CharField(blank=True, help_text='Shown as the download name; prefilled from the filename', max_length=255),
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('policy', 'Policy'), ('form', 'Form'), ('report', 'Report'), ('circular', 'Circular'), ('curriculum', 'Curriculum Material'), ('video', 'Video'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='revision_date',
            field=models.DateField(blank=True, help_text='Date of the current revision of this resource', null=True),
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='slug',
            field=models.SlugField(blank=True, help_text="Used in the resource page's public URL; generated from the name if left blank", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
