# Generated by Django 6.0.6 on 2026-07-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_folders_become_resource_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='revision_date',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.AlterField(
            model_name='resourcefolder',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="Used in the resource page's public URL; generated from the name if left blank", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
