# Generated by Django 6.0.6 on 2026-08-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_remove_resource_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='office',
            field=models.CharField(blank=True, help_text="Publishing office/organization (e.g., 'Ministry of Education')", max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='pages',
            field=models.PositiveIntegerField(blank=True, help_text='Number of pages (for documents)', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='published_date',
            field=models.DateField(blank=True, help_text='Publication date (optional, defaults to upload date)', null=True),
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sort order within parent folder (0 = no custom sort)'),
        ),
    ]
