# Generated by Django 6.0.6 on 2026-08-09 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_resourceindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefolder',
            name='resource_index_page',
            field=models.ForeignKey(blank=True, help_text='The ResourceIndexPage this folder belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_folders', to='resources.resourceindexpage'),
        ),
    ]
