# Generated by Django 6.0.6 on 2026-08-09 23:18

from django.db import migrations


def wire_folders_to_index_page(apps, schema_editor):
    """Associate all ResourceFolders with the ResourceIndexPage if it exists."""
    ResourceIndexPage = apps.get_model('resources', 'ResourceIndexPage')
    ResourceFolder = apps.get_model('resources', 'ResourceFolder')

    # Find the first (and should be only) ResourceIndexPage
    index_page = ResourceIndexPage.objects.first()
    if index_page:
        # Associate all ResourceFolders with it
        ResourceFolder.objects.filter(resource_index_page__isnull=True).update(
            resource_index_page=index_page
        )


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_resourcefolder_resource_index_page'),
        ('home', '0002_create_homepage'),  # HomePage dependency for tree positioning
    ]

    operations = [
        migrations.RunPython(wire_folders_to_index_page),
    ]
