# Generated by Django 6.0.6 on 2026-08-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_wire_resourcefolder_to_index_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefolder',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (160 chars max). Leave blank to use the folder description.', max_length=160),
        ),
    ]
