# Generated by Django 6.0.6 on 2026-08-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_resourcefolder_meta_description'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefolder',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Custom canonical URL. Leave blank to use the folder's public URL."),
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.'),
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing (OG image).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
