# Generated by Django 6.0.6 on 2026-08-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_resourcefolder_canonical_url_resourcefolder_noindex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcefolder',
            name='noindex',
        ),
    ]
