# Generated by Django 6.0.6 on 2026-08-11 00:48

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_remove_resourcefolder_noindex'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'education level',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='topics',
            field=taggit.managers.TaggableManager(blank=True, help_text='Free-form keywords, e.g. literacy, inclusive education.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='resourcefolder',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('syllabus', 'Syllabus'), ('teacher_guide', 'Teacher Guide'), ('workbook', 'Workbook'), ('assessment', 'Assessment'), ('print_pack', 'Print Pack'), ('video', 'Video'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Education stage this resource is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_folders', to='resources.educationlevel'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('levels', models.ManyToManyField(blank=True, related_name='subjects', to='resources.educationlevel')),
            ],
            options={
                'verbose_name': 'subject',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Curriculum subject. Leave blank for cross-subject material.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_folders', to='resources.subject'),
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_levels', to='resources.educationlevel')),
            ],
            options={
                'verbose_name': 'year level',
                'ordering': ['level__order', 'order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='year_levels',
            field=models.ManyToManyField(blank=True, help_text='Years/forms this resource covers. Choose several for material spanning a range; leave blank if it applies to the whole level.', related_name='resource_folders', to='resources.yearlevel'),
        ),
    ]
