# Generated by Django 6.0.6 on 2026-08-11 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_seed_curriculum_vocabulary'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefolder',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Cover shown on the resource card in the explorer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='lead',
            field=models.TextField(blank=True, help_text='Short intro shown in the resource page header. Leave blank to use the description.'),
        ),
    ]
