"""
Rename `revision_date` to `published_date`.

Hand-written rather than autogenerated: the autodetector asks interactively
whether a removed/added field pair is a rename, and running it
non-interactively drops the column and creates a new one, losing every date
already entered.
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0017_resourcefolder_cover_image_resourcefolder_lead"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resourcefolder",
            old_name="revision_date",
            new_name="published_date",
        ),
    ]
