# Generated by Django 6.0.6 on 2026-08-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_rename_revision_date_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefolder',
            name='published_date',
            field=models.DateField(blank=True, help_text='Date this resource was published. Defaults to the upload date.', null=True),
        ),
    ]
