# Generated by Django 6.0.6 on 2026-08-12 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_alter_resourcefolder_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='language',
        ),
    ]
