# Generated by Django 6.0.6 on 2026-08-13 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_remove_resource_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_levels', to='resources.educationlevel'),
        ),
    ]
