# Generated by Django 6.0.6 on 2026-08-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_alter_yearlevel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in filters and on the coverage map.'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='slug',
            field=models.SlugField(help_text='Used by the frontend to identify this level. Changing it breaks existing links that filter by this level.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='levels',
            field=models.ManyToManyField(blank=True, help_text='Levels this subject is taught at. Controls which subjects appear in the filters and as rows on the coverage map.', related_name='subjects', to='resources.educationlevel'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the subject filter.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(help_text='Used by the frontend to identify this subject. Changing it breaks existing links that filter by this subject.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='yearlevel',
            name='label',
            field=models.CharField(help_text='Shown to the public, e.g. “Year 1”.', max_length=100),
        ),
        migrations.AlterField(
            model_name='yearlevel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within the level.'),
        ),
        migrations.AlterField(
            model_name='yearlevel',
            name='slug',
            field=models.SlugField(help_text='Used by the frontend to identify this year, e.g. “y1”. Changing it breaks existing links that filter by this year.', max_length=100, unique=True),
        ),
    ]
