# Generated by Django 6.0.6 on 2026-08-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_alter_educationlevel_order_alter_educationlevel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='label',
            field=models.CharField(blank=True, help_text='Titles the file on the resource page, above the description. Also used as the download name; prefilled from the filename.', max_length=255),
        ),
    ]
