# Generated by Django 6.0.6 on 2026-08-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_alter_resource_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefolder',
            name='published_date',
            field=models.DateField(blank=True, help_text='Date this material was published. Shown on the resource page and used to sort the library; defaults to today.', null=True),
        ),
    ]
