# Generated by Django 6.0.6 on 2026-08-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_alter_resourcefolder_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefolder',
            name='slug',
            field=models.SlugField(blank=True, help_text="The last part of this folder's public web address, generated from the name. Fixed once created, so links to this folder — and to everything inside it — keep working when it's renamed.", max_length=255, unique=True),
        ),
    ]
