# Generated by Django 6.0.6 on 2026-08-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0026_alter_resourcefolder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefolder',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sort order within parent folder (0 = no custom sort)'),
        ),
    ]
