# Generated by Django 6.0.6 on 2026-08-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0028_resourcefolder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefolder',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this folder is visible on the public site. Unpublishing hides it and everything inside it.'),
        ),
    ]
