# Generated by Django 6.0.6 on 2026-07-28 06:02

import json
import uuid

import wagtail.fields
from django.db import migrations


def wrap_html_in_stream(apps, schema_editor):
    """Wrap existing RichTextField HTML into a StreamField rich_text block."""
    with schema_editor.connection.cursor() as c:
        c.execute(
            "SELECT page_ptr_id, body FROM news_newspage "
            "WHERE body IS NOT NULL AND body != ''"
        )
        for pk, html in c.fetchall():
            stream_value = json.dumps(
                [{"type": "rich_text", "value": html, "id": uuid.uuid4().hex}]
            )
            c.execute(
                "UPDATE news_newspage SET body = %s WHERE page_ptr_id = %s",
                [stream_value, pk],
            )


def unwrap_stream_to_html(apps, schema_editor):
    """Reverse: concatenate rich_text block values back into HTML."""
    with schema_editor.connection.cursor() as c:
        c.execute(
            "SELECT page_ptr_id, body FROM news_newspage "
            "WHERE body IS NOT NULL AND body != ''"
        )
        for pk, value in c.fetchall():
            try:
                blocks = json.loads(value)
                html = "".join(
                    b.get("value", "") for b in blocks if b.get("type") == "rich_text"
                )
            except (ValueError, TypeError):
                html = value
            c.execute(
                "UPDATE news_newspage SET body = %s WHERE page_ptr_id = %s",
                [html, pk],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(wrap_html_in_stream, unwrap_stream_to_html),
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('quote', 4)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the person quoted.', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Role or title of the person quoted (e.g. 'Minister of Education').", 'max_length': 200, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('quote', 1), ('attribution', 2), ('role', 3)]], {})}),
        ),
    ]
