# Generated by Django 6.0.6 on 2026-07-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsindexpage',
            name='lead',
            field=models.TextField(blank=True, help_text='Short lead paragraph shown in the page header.'),
        ),
    ]
