# Generated by Django 6.0.6 on 2026-07-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='pillars',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pillar_one_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pillar_one_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pillar_three_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pillar_three_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pillar_two_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pillar_two_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
