# Generated by Django 6.0.6 on 2026-07-23 09:00

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_aboutpage_pillar_one_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='contact_form_fields',
            field=wagtail.fields.StreamField([('text', 2), ('email', 2), ('multiline', 2), ('dropdown', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('placeholder', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (0,), {}), 4: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('options', 3)]], {})}, help_text='Input fields rendered inside the contact form.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_form_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_form_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_form_submit_text',
            field=models.CharField(blank=True, default='Send message', max_length=100),
        ),
    ]
