# Generated by Django 6.0.6 on 2026-07-23 21:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_aboutpage_contact_form_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='service_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='service_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='services',
            field=wagtail.fields.StreamField([('service', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short audience label shown as a pill on the image.', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Caption shown on the image (defaults to the heading).', 'max_length': 200, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 1), ('image', 2), ('badge', 3), ('text', 4)]], {})}, help_text='Services shown in the media accordion.'),
        ),
    ]
