# Generated by Django 6.0.7 on 2026-08-07 03:23

import django.db.models.deletion
import wagtail.fields
import wagtail_headless_preview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aboutpage_service_heading_aboutpage_service_intro_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('lead', models.TextField(blank=True, help_text='Short lead paragraph shown in the page header.')),
                ('at_a_glance', wagtail.fields.StreamField([('point', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200})}, help_text='Skimmable bullets shown above the body.')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Main body content. Use H2 headings for section titles.')),
                ('conformance_target', models.CharField(blank=True, default='WCAG 2.1 AA', max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Accessibility page',
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, 'wagtailcore.page'),
        ),
    ]
