"""
Django settings for the CMS project (config package).

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "home",
    "search",
    "resources",
    "menu",
    "news",
    "publication",
    "grapple",
    "graphene_django",
    "wagtail_headless_preview",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.postgres",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

X_FRAME_OPTIONS = "SAMEORIGIN"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Set DATABASE_URL (e.g. in cms/.env) to use Postgres; falls back to SQLite.
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Media storage: switch to S3 when AWS_STORAGE_BUCKET_NAME is set. Credentials
# come from the standard boto3 chain (env vars, instance profile, task role),
# so nothing sensitive lives in this file. Endpoint/custom-domain overrides let
# the same block target S3-compatible services (R2, MinIO, Spaces) or a CDN.
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
if AWS_STORAGE_BUCKET_NAME:
    s3_options = {
        "bucket_name": AWS_STORAGE_BUCKET_NAME,
        "file_overwrite": False,
        "default_acl": None,
        "querystring_auth": os.environ.get(
            "AWS_S3_QUERYSTRING_AUTH", "false"
        ).lower() == "true",
    }
    if region := os.environ.get("AWS_S3_REGION_NAME"):
        s3_options["region_name"] = region
    if endpoint := os.environ.get("AWS_S3_ENDPOINT_URL"):
        s3_options["endpoint_url"] = endpoint
    if custom_domain := os.environ.get("AWS_S3_CUSTOM_DOMAIN"):
        s3_options["custom_domain"] = custom_domain
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": s3_options,
    }

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

WAGTAIL_SITE_NAME = "education.gov.sb"

# Grapple / GraphQL
GRAPHENE = {
    "SCHEMA": "grapple.schema.schema",
}
GRAPPLE = {
    "APPS": ["home", "menu", "resources", "news", "publication"],
    "RICH_TEXT_FORMAT": "html",
    "EXPOSE_GRAPHIQL": True,
}

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails, and for absolute image/document URLs in GraphQL
# responses (no request context). Don't include '/admin' or a trailing slash.
WAGTAILADMIN_BASE_URL = os.environ.get(
    "WAGTAILADMIN_BASE_URL", "http://localhost:8000"
)

# Allowed file extensions for documents in the (hidden) built-in document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

# Maximum upload size for documents in bytes.
WAGTAILDOCS_MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB

# Resource library uploads.
#
# Documents are PDF only: it's the one document format that renders inline in
# the frontend previewer, needs no office software to open, and looks the same
# on every device. Office formats (docx/xlsx/pptx/odt/rtf) and archives are
# deliberately excluded — publish a PDF export instead.
#
# Media is restricted to browser-playable video, since the frontend renders it
# in a <video> element; mov/avi and similar would upload but not play. This
# list must stay in step with resources.models.VIDEO_EXTENSIONS, which decides
# what counts as video for the larger size limit and the player — there's a
# test asserting the two agree.
RESOURCE_LIBRARY_DOCUMENT_EXTENSIONS = ['pdf']
RESOURCE_LIBRARY_VIDEO_EXTENSIONS = ['mp4', 'webm', 'm4v']
RESOURCE_LIBRARY_EXTENSIONS = (
    RESOURCE_LIBRARY_DOCUMENT_EXTENSIONS + RESOURCE_LIBRARY_VIDEO_EXTENSIONS
)
RESOURCE_LIBRARY_MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB
RESOURCE_LIBRARY_VIDEO_MAX_UPLOAD_SIZE = 200 * 1024 * 1024  # 200MB

# Wagtail Headless Preview
WAGTAIL_HEADLESS_PREVIEW = {
    "CLIENT_URLS": {
        "default": "{SITE_ROOT_URL}/api/preview",
    },
    "SERVE_BASE_URL": os.environ.get("SERVE_BASE_URL", "http://localhost:3000"),
    "REDIRECT_ON_PREVIEW": True, 
    "ENFORCE_TRAILING_SLASH": True, 
}